import React from "react";
import { InteractiveExerciseProps } from "@/types/interactiveHomework";
import { Textarea } from "@/components/ui/textarea";
import { safeGetNanoSkill } from "@/utils/textObjectFixer";
import NanoSkillBadge, { NanoSkill } from "./NanoSkillBadge";

/**
 * Interface for the scenario_prompt + tasks JSON format
 * This is a non-standard AI-generated format that requires special handling
 */
interface WritingTaskContent {
  scenario_prompt: string;
  tasks: Array<{
    heading: string;
    questions: Array<{
      question: string;
      nano_skill?: string | { name: string; confidence: number; reason: string };
      confidence?: number;
      reason?: string;
    }>;
  }>;
}

interface ExerciseWritingTaskProps extends Partial<InteractiveExerciseProps> {
  content: WritingTaskContent;
  isEditing: boolean;
  viewMode: "student" | "teacher";
  liveSessionAnswer?: Record<string, any>;
  disabled?: boolean;
  onNanoSkillChange?: (taskIndex: number, questionIndex: number, nanoSkill: NanoSkill) => void;
  isSharedWorksheet?: boolean;
}

/**
 * ExerciseWritingTask - renders the scenario_prompt + tasks JSON format
 * 
 * This component handles a non-standard exercise format generated by AI that includes:
 * - scenario_prompt: Context/instruction for the entire exercise
 * - tasks: Array of sections, each with a heading and list of questions
 * 
 * Answer keys use format: "taskIndex-questionIndex" (e.g., "0-0", "0-1", "1-0")
 */
const ExerciseWritingTask: React.FC<ExerciseWritingTaskProps> = ({
  content,
  isEditing,
  viewMode,
  liveSessionAnswer,
  isInteractive = false,
  studentAnswers = {},
  onAnswerChange,
  showCorrectAnswers = false,
  disabled = false,
  onNanoSkillChange,
  isSharedWorksheet = false
}) => {
  // Validate content structure
  if (!content || !content.scenario_prompt || !Array.isArray(content.tasks)) {
    console.warn('[ExerciseWritingTask] Invalid content structure:', content);
    return (
      <div className="p-4 border border-yellow-300 bg-yellow-50 rounded-lg">
        <p className="text-yellow-800">⚠️ Unable to display exercise content. Invalid format.</p>
      </div>
    );
  }

  // Count total questions for progress tracking
  const totalQuestions = content.tasks.reduce((acc, task) => acc + (task.questions?.length || 0), 0);

  return (
    <div className="space-y-6">
      {/* Scenario/Context Box */}
      <div className="p-4 bg-accent/30 border-l-4 border-primary rounded-r-lg">
        <p className="text-foreground font-medium leading-relaxed">
          {content.scenario_prompt}
        </p>
      </div>

      {/* Tasks */}
      {content.tasks.map((task, taskIndex) => (
        <div key={taskIndex} className="space-y-4">
          {/* Task Heading */}
          {task.heading && (
            <h4 className="text-lg font-semibold text-foreground border-b border-border pb-2">
              {task.heading}
            </h4>
          )}

          {/* Questions */}
          <div className="space-y-4 pl-2 md:pl-4">
            {task.questions?.map((q, qIndex) => {
              // Generate unique answer key for this question
              const answerKey = `${taskIndex}-${qIndex}`;
              const studentAnswer = studentAnswers[answerKey] || '';
              const liveAnswer = liveSessionAnswer?.[answerKey];
              
              // Extract nano_skill from question
              const nanoSkill = safeGetNanoSkill(q);
              const showNanoSkill = viewMode === 'teacher' && !isSharedWorksheet && nanoSkill;
              
              // Get question text
              const questionText = typeof q === 'string' ? q : (q.question || '');
              
              return (
                <div key={qIndex} className="border rounded-lg p-3 bg-card">
                  {/* Question header with number and nano_skill */}
                  <div className="flex items-start justify-between gap-2 mb-2 flex-wrap">
                    <p className="font-medium text-foreground flex-grow">
                      {qIndex + 1}. {questionText}
                    </p>
                    
                    {/* NanoSkill Badge for teachers */}
                    {showNanoSkill && (
                      <NanoSkillBadge
                        nanoSkill={nanoSkill}
                        isEditing={isEditing}
                        onEdit={onNanoSkillChange 
                          ? (ns) => onNanoSkillChange(taskIndex, qIndex, ns) 
                          : undefined
                        }
                      />
                    )}
                  </div>
                  
                  {/* Live Session: show student answer for teacher */}
                  {viewMode === 'teacher' && liveAnswer !== undefined && (
                    <div className="mb-2 p-2 bg-accent/50 border border-primary/30 rounded text-primary text-sm">
                      <span className="font-medium">[Student's answer]: </span>
                      {liveAnswer}
                    </div>
                  )}
                  
                  {/* Interactive answer textarea */}
                  {isInteractive && (
                    <Textarea
                      value={studentAnswer}
                      onChange={(e) => onAnswerChange?.(answerKey as any, e.target.value)}
                      placeholder="Write your answer here..."
                      className={`min-h-[80px] resize-y ${disabled ? 'opacity-60 cursor-not-allowed' : ''}`}
                      disabled={disabled}
                    />
                  )}
                  
                  {/* Show submitted answer when viewing results */}
                  {showCorrectAnswers && studentAnswer && !isInteractive && (
                    <div className="mt-2 p-2 bg-muted rounded text-sm">
                      <span className="font-medium">Answer: </span>
                      {studentAnswer}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ))}

      {/* Summary for teacher view */}
      {viewMode === 'teacher' && !isInteractive && (
        <div className="text-sm text-muted-foreground mt-4 pt-2 border-t">
          📝 Total questions: {totalQuestions}
        </div>
      )}
    </div>
  );
};

export default ExerciseWritingTask;
