/**
 * Meeting link utilities for Edooqoo.
 * 
 * Auto-generated meeting links are ONLY created via Google Calendar API
 * (gcal-sync edge function, action: create_permanent_room).
 * No local fallback generation (Jitsi, deterministic hashes, etc.).
 */

/**
 * Check if a link is a legacy auto-generated link (Jitsi or old lookup pattern).
 * Used only for backward compatibility detection during migration period.
 * New code should use meeting_link_mode from calendar_student_settings instead.
 */
export function isLegacyAutoGeneratedLink(link: string): boolean {
  return link.startsWith('https://meet.jit.si/edooqoo-') || link.includes('meet.google.com/lookup/');
}
