/**
 * Generate a deterministic, permanent meeting link for a teacher-student pair.
 * Uses Google Calendar API to create a real Google Meet room when GCal is connected,
 * otherwise falls back to Jitsi Meet.
 */

/**
 * Generate a deterministic Jitsi Meet fallback link (no API required).
 */
export function generateFallbackMeetingLink(teacherId: string, studentId: string): string {
  const raw = `${teacherId}-${studentId}`;
  const hash = btoa(raw).replace(/[^a-zA-Z0-9]/g, '').slice(0, 16).toLowerCase();
  return `https://meet.jit.si/edooqoo-${hash}`;
}

/**
 * Check if a link is an auto-generated default (Jitsi or old lookup pattern).
 */
export function isAutoGeneratedLink(link: string): boolean {
  return link.startsWith('https://meet.jit.si/edooqoo-') || link.includes('meet.google.com/lookup/');
}
