/**
 * DSLM Event Types - Layer A (Facts)
 * Canonical event type definitions for the student event log.
 * 
 * IMPORTANT: These are the ONLY valid event_type/event_source pairs.
 * All old naming variants have been normalized via SQL migration.
 */

// =====================================================
// Event Sources - where the event originates
// =====================================================
export type EventSource = 
  | 'homework'      // From homework assignments
  | 'flashcard'     // From flashcard reviews
  | 'test'          // From tests (student_tests)
  | 'worksheet'     // From shared worksheet interactions
  | 'teacher'       // Manual teacher observation/input
  | 'welcome_test'  // From welcome test flow
  | 'system';       // Auto-generated by system

// =====================================================
// Event Types - canonical naming (no aliases!)
// =====================================================
export type StudentEventType = 
  // Student learning activity (worksheet + homework answers)
  | 'student_learning_activity'   // source: worksheet | homework
  
  // Homework lifecycle
  | 'homework_submitted'          // source: homework

  // Flashcard events
  | 'flashcard_review'            // source: flashcard

  // AI evaluation triggers
  | '10min_AI_evaluation'         // source: worksheet
  | 'create_hw_AI_evaluation'     // source: worksheet
  | 'submit_hw_AI_evaluation'     // source: homework

  // Teacher events
  | 'mark_done_evaluation'        // source: teacher (was exercise_mastery_evaluation)
  | 'teacher_observation'         // source: teacher
  | 'knowledge_entry_added'       // source: teacher

  // Test events
  | 'test_answer_submitted'       // source: test | welcome_test
  ;

// =====================================================
// Element Types - skill categories
// =====================================================
export type ElementType = 
  | 'grammar'
  | 'vocabulary'
  | 'speaking'
  | 'listening'
  | 'writing'
  | 'reading'
  | 'pronunciation';

// =====================================================
// Event Payloads
// =====================================================

export interface FlashcardReviewPayload {
  card_id: string;
  set_id: string;
  direction: number;
  card_front: string;
  card_back: string;
  mastery: number;         // 0-100 weighted (0=fail, 50=1st correct, 70=2nd, 90=well-known, 100=mastered)
  easiness_factor: number;
  repetition: number;
  interval_days: number;
  total_reviews: number;
  time_spent_seconds: number;
}

export interface LearningActivityPayload {
  answer_id: string;
  exercise_index: number;
  exercise_type: string;
  time_spent_seconds: number;
  is_submitted?: boolean;  // Only for homework
  nano_skill_ratings: Array<{
    name: string;
    reason: string;
    mastery: number;       // 0-100
    hasValue: boolean;
    question_index: number;
  }>;
}

export interface TestAnswerPayload {
  question_id: string;
  question_type: string;
  question_index: number;
  is_correct: boolean | null;
  time_spent_seconds: number | null;
  difficulty_level: number | null;
}

// Welcome test types removed - now uses test_answer_submitted with event_source='welcome_test'

export interface TeacherObservationPayload {
  observation_type: 'strength' | 'weakness' | 'behavior' | 'progress' | 'note';
  claim: string;
  weight: number;
  related_skill_ids?: string[];
}

export interface MarkDoneEvaluationPayload {
  exercise_index: number;
  exercise_title: string;
  exercise_type: string;
  nano_skill_ratings: Array<{
    name: string;
    reason: string;
    mastery: number;
  }>;
}

export interface KnowledgeEntryPayload {
  category: string;
  tags: string[];
  entry_source: string;
}

// =====================================================
// Main Event Interface
// =====================================================
export interface StudentEvent {
  id: string;
  student_id: string;
  teacher_id: string;
  event_type: StudentEventType;
  event_source: EventSource;
  source_id: string | null;
  event_payload: Record<string, unknown>;
  skill_ids: string[] | null;
  element_type: ElementType | null;
  session_id: string | null;
  mastery: number | null;
  created_at: string;
  is_processed: boolean;
}

// =====================================================
// Input types for creating events
// =====================================================
export interface CreateStudentEventInput {
  student_id: string;
  teacher_id: string;
  event_type: StudentEventType;
  event_source: EventSource;
  source_id?: string;
  event_payload?: Record<string, unknown>;
  skill_ids?: string[];
  element_type?: ElementType;
  session_id?: string;
}

// =====================================================
// Event filters for querying
// =====================================================
export interface StudentEventFilters {
  event_types?: StudentEventType[];
  event_sources?: EventSource[];
  element_types?: ElementType[];
  date_from?: string;
  date_to?: string;
  is_processed?: boolean;
  limit?: number;
}

// =====================================================
// Event statistics
// =====================================================
export interface StudentEventStats {
  total_events: number;
  events_by_type: Record<StudentEventType, number>;
  events_by_source: Record<EventSource, number>;
  events_last_7_days: number;
  events_last_30_days: number;
  last_event_at: string | null;
}
